package com.woostar.tender.mapper;

import com.woostar.tender.model.SGCCProjectDetail;
import com.woostar.tender.model.example.SGCCProjectDetailExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ISGCCProjectDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    long countByExample(SGCCProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    int deleteByExample(SGCCProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    int insert(SGCCProjectDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    int insertSelective(SGCCProjectDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    List<SGCCProjectDetail> selectByExample(SGCCProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    SGCCProjectDetail selectByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SGCCProjectDetail record, @Param("example") SGCCProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SGCCProjectDetail record, @Param("example") SGCCProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SGCCProjectDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SGCCProjectDetail record);
}