package com.woostar.tender.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_detail
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProjectDetail {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   项目编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     * Database Column Remarks:
     *   项目名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     * Database Column Remarks:
     *   项目内容描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.project_description
     *
     * @mbg.generated
     */
    private String projectDescription;

    /**
     * Database Column Remarks:
     *   公告发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.tender_announce_time
     *
     * @mbg.generated
     */
    private Date tenderAnnounceTime;

    /**
     * Database Column Remarks:
     *   招标截止时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.tender_deadline
     *
     * @mbg.generated
     */
    private Date tenderDeadline;

    /**
     * Database Column Remarks:
     *   联系人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.contact_person
     *
     * @mbg.generated
     */
    private String contactPerson;

    /**
     * Database Column Remarks:
     *   联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.contact_phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   项目信息来源网站
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.source_website
     *
     * @mbg.generated
     */
    private String sourceWebsite;

    /**
     * Database Column Remarks:
     *   项目信息链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.source_url
     *
     * @mbg.generated
     */
    private String sourceUrl;

    /**
     * Database Column Remarks:
     *   记录创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   记录更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_detail.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.id
     *
     * @return the value of project_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.id
     *
     * @param id the value for project_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.project_id
     *
     * @return the value of project_detail.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.project_id
     *
     * @param projectId the value for project_detail.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.project_name
     *
     * @return the value of project_detail.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.project_name
     *
     * @param projectName the value for project_detail.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.project_description
     *
     * @return the value of project_detail.project_description
     *
     * @mbg.generated
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.project_description
     *
     * @param projectDescription the value for project_detail.project_description
     *
     * @mbg.generated
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription == null ? null : projectDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.tender_announce_time
     *
     * @return the value of project_detail.tender_announce_time
     *
     * @mbg.generated
     */
    public Date getTenderAnnounceTime() {
        return tenderAnnounceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.tender_announce_time
     *
     * @param tenderAnnounceTime the value for project_detail.tender_announce_time
     *
     * @mbg.generated
     */
    public void setTenderAnnounceTime(Date tenderAnnounceTime) {
        this.tenderAnnounceTime = tenderAnnounceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.tender_deadline
     *
     * @return the value of project_detail.tender_deadline
     *
     * @mbg.generated
     */
    public Date getTenderDeadline() {
        return tenderDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.tender_deadline
     *
     * @param tenderDeadline the value for project_detail.tender_deadline
     *
     * @mbg.generated
     */
    public void setTenderDeadline(Date tenderDeadline) {
        this.tenderDeadline = tenderDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.contact_person
     *
     * @return the value of project_detail.contact_person
     *
     * @mbg.generated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.contact_person
     *
     * @param contactPerson the value for project_detail.contact_person
     *
     * @mbg.generated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.contact_phone
     *
     * @return the value of project_detail.contact_phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.contact_phone
     *
     * @param contactPhone the value for project_detail.contact_phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.remark
     *
     * @return the value of project_detail.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.remark
     *
     * @param remark the value for project_detail.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.source_website
     *
     * @return the value of project_detail.source_website
     *
     * @mbg.generated
     */
    public String getSourceWebsite() {
        return sourceWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.source_website
     *
     * @param sourceWebsite the value for project_detail.source_website
     *
     * @mbg.generated
     */
    public void setSourceWebsite(String sourceWebsite) {
        this.sourceWebsite = sourceWebsite == null ? null : sourceWebsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.source_url
     *
     * @return the value of project_detail.source_url
     *
     * @mbg.generated
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.source_url
     *
     * @param sourceUrl the value for project_detail.source_url
     *
     * @mbg.generated
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.create_time
     *
     * @return the value of project_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.create_time
     *
     * @param createTime the value for project_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_detail.update_time
     *
     * @return the value of project_detail.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_detail.update_time
     *
     * @param updateTime the value for project_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table project_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        projectId("project_id", "projectId", "VARCHAR", false),
        projectName("project_name", "projectName", "VARCHAR", false),
        projectDescription("project_description", "projectDescription", "VARCHAR", false),
        tenderAnnounceTime("tender_announce_time", "tenderAnnounceTime", "TIMESTAMP", false),
        tenderDeadline("tender_deadline", "tenderDeadline", "TIMESTAMP", false),
        contactPerson("contact_person", "contactPerson", "VARCHAR", false),
        contactPhone("contact_phone", "contactPhone", "VARCHAR", false),
        remark("remark", "remark", "VARCHAR", false),
        sourceWebsite("source_website", "sourceWebsite", "VARCHAR", false),
        sourceUrl("source_url", "sourceUrl", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}