package com.woostar.tender.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sgcc_project_detail
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SGCCProjectDetail {
    /**
     * Database Column Remarks:
     *   项目编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     * Database Column Remarks:
     *   项目名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     * Database Column Remarks:
     *   截标时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.closing_time
     *
     * @mbg.generated
     */
    private Date closingTime;

    /**
     * Database Column Remarks:
     *   开标时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.opening_time
     *
     * @mbg.generated
     */
    private Date openingTime;

    /**
     * Database Column Remarks:
     *   项目类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.project_type
     *
     * @mbg.generated
     */
    private String projectType;

    /**
     * Database Column Remarks:
     *   标书费用形式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.bid_payment_mode
     *
     * @mbg.generated
     */
    private String bidPaymentMode;

    /**
     * Database Column Remarks:
     *   标书购买截止时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.bid_purchase_deadline
     *
     * @mbg.generated
     */
    private Date bidPurchaseDeadline;

    /**
     * Database Column Remarks:
     *   招标人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.tender_agency
     *
     * @mbg.generated
     */
    private String tenderAgency;

    /**
     * Database Column Remarks:
     *   代理机构
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.proxy_agency
     *
     * @mbg.generated
     */
    private String proxyAgency;

    /**
     * Database Column Remarks:
     *   联系人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.contact_person
     *
     * @mbg.generated
     */
    private String contactPerson;

    /**
     * Database Column Remarks:
     *   联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.contact_phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     * Database Column Remarks:
     *   传真
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.fox
     *
     * @mbg.generated
     */
    private String fox;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.e_mail
     *
     * @mbg.generated
     */
    private String eMail;

    /**
     * Database Column Remarks:
     *   记录创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   记录更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sgcc_project_detail.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.project_id
     *
     * @return the value of sgcc_project_detail.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.project_id
     *
     * @param projectId the value for sgcc_project_detail.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.project_name
     *
     * @return the value of sgcc_project_detail.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.project_name
     *
     * @param projectName the value for sgcc_project_detail.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.closing_time
     *
     * @return the value of sgcc_project_detail.closing_time
     *
     * @mbg.generated
     */
    public Date getClosingTime() {
        return closingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.closing_time
     *
     * @param closingTime the value for sgcc_project_detail.closing_time
     *
     * @mbg.generated
     */
    public void setClosingTime(Date closingTime) {
        this.closingTime = closingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.opening_time
     *
     * @return the value of sgcc_project_detail.opening_time
     *
     * @mbg.generated
     */
    public Date getOpeningTime() {
        return openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.opening_time
     *
     * @param openingTime the value for sgcc_project_detail.opening_time
     *
     * @mbg.generated
     */
    public void setOpeningTime(Date openingTime) {
        this.openingTime = openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.project_type
     *
     * @return the value of sgcc_project_detail.project_type
     *
     * @mbg.generated
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.project_type
     *
     * @param projectType the value for sgcc_project_detail.project_type
     *
     * @mbg.generated
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType == null ? null : projectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.bid_payment_mode
     *
     * @return the value of sgcc_project_detail.bid_payment_mode
     *
     * @mbg.generated
     */
    public String getBidPaymentMode() {
        return bidPaymentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.bid_payment_mode
     *
     * @param bidPaymentMode the value for sgcc_project_detail.bid_payment_mode
     *
     * @mbg.generated
     */
    public void setBidPaymentMode(String bidPaymentMode) {
        this.bidPaymentMode = bidPaymentMode == null ? null : bidPaymentMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.bid_purchase_deadline
     *
     * @return the value of sgcc_project_detail.bid_purchase_deadline
     *
     * @mbg.generated
     */
    public Date getBidPurchaseDeadline() {
        return bidPurchaseDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.bid_purchase_deadline
     *
     * @param bidPurchaseDeadline the value for sgcc_project_detail.bid_purchase_deadline
     *
     * @mbg.generated
     */
    public void setBidPurchaseDeadline(Date bidPurchaseDeadline) {
        this.bidPurchaseDeadline = bidPurchaseDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.tender_agency
     *
     * @return the value of sgcc_project_detail.tender_agency
     *
     * @mbg.generated
     */
    public String getTenderAgency() {
        return tenderAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.tender_agency
     *
     * @param tenderAgency the value for sgcc_project_detail.tender_agency
     *
     * @mbg.generated
     */
    public void setTenderAgency(String tenderAgency) {
        this.tenderAgency = tenderAgency == null ? null : tenderAgency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.proxy_agency
     *
     * @return the value of sgcc_project_detail.proxy_agency
     *
     * @mbg.generated
     */
    public String getProxyAgency() {
        return proxyAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.proxy_agency
     *
     * @param proxyAgency the value for sgcc_project_detail.proxy_agency
     *
     * @mbg.generated
     */
    public void setProxyAgency(String proxyAgency) {
        this.proxyAgency = proxyAgency == null ? null : proxyAgency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.contact_person
     *
     * @return the value of sgcc_project_detail.contact_person
     *
     * @mbg.generated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.contact_person
     *
     * @param contactPerson the value for sgcc_project_detail.contact_person
     *
     * @mbg.generated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.contact_phone
     *
     * @return the value of sgcc_project_detail.contact_phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.contact_phone
     *
     * @param contactPhone the value for sgcc_project_detail.contact_phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.fox
     *
     * @return the value of sgcc_project_detail.fox
     *
     * @mbg.generated
     */
    public String getFox() {
        return fox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.fox
     *
     * @param fox the value for sgcc_project_detail.fox
     *
     * @mbg.generated
     */
    public void setFox(String fox) {
        this.fox = fox == null ? null : fox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.e_mail
     *
     * @return the value of sgcc_project_detail.e_mail
     *
     * @mbg.generated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.e_mail
     *
     * @param eMail the value for sgcc_project_detail.e_mail
     *
     * @mbg.generated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.create_time
     *
     * @return the value of sgcc_project_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.create_time
     *
     * @param createTime the value for sgcc_project_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sgcc_project_detail.update_time
     *
     * @return the value of sgcc_project_detail.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sgcc_project_detail.update_time
     *
     * @param updateTime the value for sgcc_project_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        projectId("project_id", "projectId", "VARCHAR", false),
        projectName("project_name", "projectName", "VARCHAR", false),
        closingTime("closing_time", "closingTime", "TIMESTAMP", false),
        openingTime("opening_time", "openingTime", "TIMESTAMP", false),
        projectType("project_type", "projectType", "VARCHAR", false),
        bidPaymentMode("bid_payment_mode", "bidPaymentMode", "VARCHAR", false),
        bidPurchaseDeadline("bid_purchase_deadline", "bidPurchaseDeadline", "TIMESTAMP", false),
        tenderAgency("tender_agency", "tenderAgency", "VARCHAR", false),
        proxyAgency("proxy_agency", "proxyAgency", "VARCHAR", false),
        contactPerson("contact_person", "contactPerson", "VARCHAR", false),
        contactPhone("contact_phone", "contactPhone", "VARCHAR", false),
        fox("fox", "fox", "VARCHAR", false),
        eMail("e_mail", "eMail", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}