package com.woostar.tender.model.example;

import com.woostar.tender.model.ProjectDetail;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public ProjectDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public ProjectDetailExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public ProjectDetailExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andReportNumberIsNull() {
            addCriterion("report_number is null");
            return (Criteria) this;
        }

        public Criteria andReportNumberIsNotNull() {
            addCriterion("report_number is not null");
            return (Criteria) this;
        }

        public Criteria andReportNumberEqualTo(String value) {
            addCriterion("report_number =", value, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberNotEqualTo(String value) {
            addCriterion("report_number <>", value, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberGreaterThan(String value) {
            addCriterion("report_number >", value, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberGreaterThanOrEqualTo(String value) {
            addCriterion("report_number >=", value, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberLessThan(String value) {
            addCriterion("report_number <", value, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberLessThanOrEqualTo(String value) {
            addCriterion("report_number <=", value, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberLike(String value) {
            addCriterion("report_number like", value, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberNotLike(String value) {
            addCriterion("report_number not like", value, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberIn(List<String> values) {
            addCriterion("report_number in", values, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberNotIn(List<String> values) {
            addCriterion("report_number not in", values, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberBetween(String value1, String value2) {
            addCriterion("report_number between", value1, value2, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNumberNotBetween(String value1, String value2) {
            addCriterion("report_number not between", value1, value2, "reportNumber");
            return (Criteria) this;
        }

        public Criteria andReportNameIsNull() {
            addCriterion("report_name is null");
            return (Criteria) this;
        }

        public Criteria andReportNameIsNotNull() {
            addCriterion("report_name is not null");
            return (Criteria) this;
        }

        public Criteria andReportNameEqualTo(String value) {
            addCriterion("report_name =", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotEqualTo(String value) {
            addCriterion("report_name <>", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameGreaterThan(String value) {
            addCriterion("report_name >", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameGreaterThanOrEqualTo(String value) {
            addCriterion("report_name >=", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameLessThan(String value) {
            addCriterion("report_name <", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameLessThanOrEqualTo(String value) {
            addCriterion("report_name <=", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameLike(String value) {
            addCriterion("report_name like", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotLike(String value) {
            addCriterion("report_name not like", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameIn(List<String> values) {
            addCriterion("report_name in", values, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotIn(List<String> values) {
            addCriterion("report_name not in", values, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameBetween(String value1, String value2) {
            addCriterion("report_name between", value1, value2, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotBetween(String value1, String value2) {
            addCriterion("report_name not between", value1, value2, "reportName");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberIsNull() {
            addCriterion("tender_registration_number is null");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberIsNotNull() {
            addCriterion("tender_registration_number is not null");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberEqualTo(String value) {
            addCriterion("tender_registration_number =", value, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberNotEqualTo(String value) {
            addCriterion("tender_registration_number <>", value, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberGreaterThan(String value) {
            addCriterion("tender_registration_number >", value, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberGreaterThanOrEqualTo(String value) {
            addCriterion("tender_registration_number >=", value, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberLessThan(String value) {
            addCriterion("tender_registration_number <", value, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberLessThanOrEqualTo(String value) {
            addCriterion("tender_registration_number <=", value, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberLike(String value) {
            addCriterion("tender_registration_number like", value, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberNotLike(String value) {
            addCriterion("tender_registration_number not like", value, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberIn(List<String> values) {
            addCriterion("tender_registration_number in", values, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberNotIn(List<String> values) {
            addCriterion("tender_registration_number not in", values, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberBetween(String value1, String value2) {
            addCriterion("tender_registration_number between", value1, value2, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderRegistrationNumberNotBetween(String value1, String value2) {
            addCriterion("tender_registration_number not between", value1, value2, "tenderRegistrationNumber");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameIsNull() {
            addCriterion("tender_project_name is null");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameIsNotNull() {
            addCriterion("tender_project_name is not null");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameEqualTo(String value) {
            addCriterion("tender_project_name =", value, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameNotEqualTo(String value) {
            addCriterion("tender_project_name <>", value, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameGreaterThan(String value) {
            addCriterion("tender_project_name >", value, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("tender_project_name >=", value, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameLessThan(String value) {
            addCriterion("tender_project_name <", value, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameLessThanOrEqualTo(String value) {
            addCriterion("tender_project_name <=", value, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameLike(String value) {
            addCriterion("tender_project_name like", value, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameNotLike(String value) {
            addCriterion("tender_project_name not like", value, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameIn(List<String> values) {
            addCriterion("tender_project_name in", values, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameNotIn(List<String> values) {
            addCriterion("tender_project_name not in", values, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameBetween(String value1, String value2) {
            addCriterion("tender_project_name between", value1, value2, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderProjectNameNotBetween(String value1, String value2) {
            addCriterion("tender_project_name not between", value1, value2, "tenderProjectName");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonIsNull() {
            addCriterion("tender_contact_person is null");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonIsNotNull() {
            addCriterion("tender_contact_person is not null");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonEqualTo(String value) {
            addCriterion("tender_contact_person =", value, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonNotEqualTo(String value) {
            addCriterion("tender_contact_person <>", value, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonGreaterThan(String value) {
            addCriterion("tender_contact_person >", value, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonGreaterThanOrEqualTo(String value) {
            addCriterion("tender_contact_person >=", value, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonLessThan(String value) {
            addCriterion("tender_contact_person <", value, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonLessThanOrEqualTo(String value) {
            addCriterion("tender_contact_person <=", value, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonLike(String value) {
            addCriterion("tender_contact_person like", value, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonNotLike(String value) {
            addCriterion("tender_contact_person not like", value, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonIn(List<String> values) {
            addCriterion("tender_contact_person in", values, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonNotIn(List<String> values) {
            addCriterion("tender_contact_person not in", values, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonBetween(String value1, String value2) {
            addCriterion("tender_contact_person between", value1, value2, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonNotBetween(String value1, String value2) {
            addCriterion("tender_contact_person not between", value1, value2, "tenderContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneIsNull() {
            addCriterion("tender_contact_person_phone is null");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneIsNotNull() {
            addCriterion("tender_contact_person_phone is not null");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneEqualTo(String value) {
            addCriterion("tender_contact_person_phone =", value, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneNotEqualTo(String value) {
            addCriterion("tender_contact_person_phone <>", value, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneGreaterThan(String value) {
            addCriterion("tender_contact_person_phone >", value, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("tender_contact_person_phone >=", value, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneLessThan(String value) {
            addCriterion("tender_contact_person_phone <", value, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneLessThanOrEqualTo(String value) {
            addCriterion("tender_contact_person_phone <=", value, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneLike(String value) {
            addCriterion("tender_contact_person_phone like", value, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneNotLike(String value) {
            addCriterion("tender_contact_person_phone not like", value, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneIn(List<String> values) {
            addCriterion("tender_contact_person_phone in", values, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneNotIn(List<String> values) {
            addCriterion("tender_contact_person_phone not in", values, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneBetween(String value1, String value2) {
            addCriterion("tender_contact_person_phone between", value1, value2, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderContactPersonPhoneNotBetween(String value1, String value2) {
            addCriterion("tender_contact_person_phone not between", value1, value2, "tenderContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonIsNull() {
            addCriterion("tender_proxy_contact_person is null");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonIsNotNull() {
            addCriterion("tender_proxy_contact_person is not null");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonEqualTo(String value) {
            addCriterion("tender_proxy_contact_person =", value, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonNotEqualTo(String value) {
            addCriterion("tender_proxy_contact_person <>", value, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonGreaterThan(String value) {
            addCriterion("tender_proxy_contact_person >", value, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonGreaterThanOrEqualTo(String value) {
            addCriterion("tender_proxy_contact_person >=", value, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonLessThan(String value) {
            addCriterion("tender_proxy_contact_person <", value, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonLessThanOrEqualTo(String value) {
            addCriterion("tender_proxy_contact_person <=", value, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonLike(String value) {
            addCriterion("tender_proxy_contact_person like", value, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonNotLike(String value) {
            addCriterion("tender_proxy_contact_person not like", value, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonIn(List<String> values) {
            addCriterion("tender_proxy_contact_person in", values, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonNotIn(List<String> values) {
            addCriterion("tender_proxy_contact_person not in", values, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonBetween(String value1, String value2) {
            addCriterion("tender_proxy_contact_person between", value1, value2, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonNotBetween(String value1, String value2) {
            addCriterion("tender_proxy_contact_person not between", value1, value2, "tenderProxyContactPerson");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneIsNull() {
            addCriterion("tender_proxy_contact_person_phone is null");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneIsNotNull() {
            addCriterion("tender_proxy_contact_person_phone is not null");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneEqualTo(String value) {
            addCriterion("tender_proxy_contact_person_phone =", value, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneNotEqualTo(String value) {
            addCriterion("tender_proxy_contact_person_phone <>", value, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneGreaterThan(String value) {
            addCriterion("tender_proxy_contact_person_phone >", value, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("tender_proxy_contact_person_phone >=", value, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneLessThan(String value) {
            addCriterion("tender_proxy_contact_person_phone <", value, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneLessThanOrEqualTo(String value) {
            addCriterion("tender_proxy_contact_person_phone <=", value, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneLike(String value) {
            addCriterion("tender_proxy_contact_person_phone like", value, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneNotLike(String value) {
            addCriterion("tender_proxy_contact_person_phone not like", value, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneIn(List<String> values) {
            addCriterion("tender_proxy_contact_person_phone in", values, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneNotIn(List<String> values) {
            addCriterion("tender_proxy_contact_person_phone not in", values, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneBetween(String value1, String value2) {
            addCriterion("tender_proxy_contact_person_phone between", value1, value2, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProxyContactPersonPhoneNotBetween(String value1, String value2) {
            addCriterion("tender_proxy_contact_person_phone not between", value1, value2, "tenderProxyContactPersonPhone");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionIsNull() {
            addCriterion("tender_project_description is null");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionIsNotNull() {
            addCriterion("tender_project_description is not null");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionEqualTo(String value) {
            addCriterion("tender_project_description =", value, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionNotEqualTo(String value) {
            addCriterion("tender_project_description <>", value, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionGreaterThan(String value) {
            addCriterion("tender_project_description >", value, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("tender_project_description >=", value, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionLessThan(String value) {
            addCriterion("tender_project_description <", value, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionLessThanOrEqualTo(String value) {
            addCriterion("tender_project_description <=", value, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionLike(String value) {
            addCriterion("tender_project_description like", value, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionNotLike(String value) {
            addCriterion("tender_project_description not like", value, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionIn(List<String> values) {
            addCriterion("tender_project_description in", values, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionNotIn(List<String> values) {
            addCriterion("tender_project_description not in", values, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionBetween(String value1, String value2) {
            addCriterion("tender_project_description between", value1, value2, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andTenderProjectDescriptionNotBetween(String value1, String value2) {
            addCriterion("tender_project_description not between", value1, value2, "tenderProjectDescription");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeIsNull() {
            addCriterion("announcement_release_time is null");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeIsNotNull() {
            addCriterion("announcement_release_time is not null");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeEqualTo(Date value) {
            addCriterion("announcement_release_time =", value, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeNotEqualTo(Date value) {
            addCriterion("announcement_release_time <>", value, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeGreaterThan(Date value) {
            addCriterion("announcement_release_time >", value, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("announcement_release_time >=", value, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeLessThan(Date value) {
            addCriterion("announcement_release_time <", value, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeLessThanOrEqualTo(Date value) {
            addCriterion("announcement_release_time <=", value, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeIn(List<Date> values) {
            addCriterion("announcement_release_time in", values, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeNotIn(List<Date> values) {
            addCriterion("announcement_release_time not in", values, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeBetween(Date value1, Date value2) {
            addCriterion("announcement_release_time between", value1, value2, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andAnnouncementReleaseTimeNotBetween(Date value1, Date value2) {
            addCriterion("announcement_release_time not between", value1, value2, "announcementReleaseTime");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineIsNull() {
            addCriterion("tender_deadline is null");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineIsNotNull() {
            addCriterion("tender_deadline is not null");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineEqualTo(Date value) {
            addCriterion("tender_deadline =", value, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineNotEqualTo(Date value) {
            addCriterion("tender_deadline <>", value, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineGreaterThan(Date value) {
            addCriterion("tender_deadline >", value, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("tender_deadline >=", value, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineLessThan(Date value) {
            addCriterion("tender_deadline <", value, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("tender_deadline <=", value, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineIn(List<Date> values) {
            addCriterion("tender_deadline in", values, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineNotIn(List<Date> values) {
            addCriterion("tender_deadline not in", values, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineBetween(Date value1, Date value2) {
            addCriterion("tender_deadline between", value1, value2, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("tender_deadline not between", value1, value2, "tenderDeadline");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tender_project_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private ProjectDetailExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(ProjectDetailExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public ProjectDetailExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNumberEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_number = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNumberNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_number <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNumberGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_number > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNumberGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_number >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNumberLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_number < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNumberLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_number <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNameEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNameNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNameGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNameGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNameLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andReportNameLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("report_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderRegistrationNumberEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_registration_number = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderRegistrationNumberNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_registration_number <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderRegistrationNumberGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_registration_number > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderRegistrationNumberGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_registration_number >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderRegistrationNumberLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_registration_number < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderRegistrationNumberLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_registration_number <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectNameEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectNameNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectNameGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectNameGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectNameLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectNameLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonPhoneEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person_phone = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonPhoneNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person_phone <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonPhoneGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person_phone > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonPhoneGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person_phone >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonPhoneLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person_phone < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderContactPersonPhoneLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_contact_person_phone <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonPhoneEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person_phone = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonPhoneNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person_phone <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonPhoneGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person_phone > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonPhoneGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person_phone >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonPhoneLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person_phone < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProxyContactPersonPhoneLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_proxy_contact_person_phone <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectDescriptionEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_description = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectDescriptionNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_description <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectDescriptionGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_description > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectDescriptionGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_description >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectDescriptionLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_description < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderProjectDescriptionLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_project_description <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAnnouncementReleaseTimeEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("announcement_release_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAnnouncementReleaseTimeNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("announcement_release_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAnnouncementReleaseTimeGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("announcement_release_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAnnouncementReleaseTimeGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("announcement_release_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAnnouncementReleaseTimeLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("announcement_release_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAnnouncementReleaseTimeLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("announcement_release_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderDeadlineEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_deadline = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderDeadlineNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_deadline <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderDeadlineGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_deadline > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderDeadlineGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_deadline >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderDeadlineLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_deadline < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderDeadlineLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_deadline <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRemarkEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("remark = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRemarkNotEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("remark <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRemarkGreaterThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("remark > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRemarkGreaterThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("remark >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRemarkLessThanColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("remark < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andRemarkLessThanOrEqualToColumn(ProjectDetail.Column column) {
            addCriterion(new StringBuilder("remark <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table tender_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table tender_project_detail
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tender_project_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}