package com.woostar.tender.model.example;

import com.woostar.tender.model.SGCCProjectDetail;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SGCCProjectDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public SGCCProjectDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public SGCCProjectDetailExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public SGCCProjectDetailExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andClosingTimeIsNull() {
            addCriterion("closing_time is null");
            return (Criteria) this;
        }

        public Criteria andClosingTimeIsNotNull() {
            addCriterion("closing_time is not null");
            return (Criteria) this;
        }

        public Criteria andClosingTimeEqualTo(Date value) {
            addCriterion("closing_time =", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeNotEqualTo(Date value) {
            addCriterion("closing_time <>", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeGreaterThan(Date value) {
            addCriterion("closing_time >", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("closing_time >=", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeLessThan(Date value) {
            addCriterion("closing_time <", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeLessThanOrEqualTo(Date value) {
            addCriterion("closing_time <=", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeIn(List<Date> values) {
            addCriterion("closing_time in", values, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeNotIn(List<Date> values) {
            addCriterion("closing_time not in", values, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeBetween(Date value1, Date value2) {
            addCriterion("closing_time between", value1, value2, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeNotBetween(Date value1, Date value2) {
            addCriterion("closing_time not between", value1, value2, "closingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeIsNull() {
            addCriterion("opening_time is null");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeIsNotNull() {
            addCriterion("opening_time is not null");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeEqualTo(Date value) {
            addCriterion("opening_time =", value, "openingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeNotEqualTo(Date value) {
            addCriterion("opening_time <>", value, "openingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeGreaterThan(Date value) {
            addCriterion("opening_time >", value, "openingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("opening_time >=", value, "openingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeLessThan(Date value) {
            addCriterion("opening_time <", value, "openingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeLessThanOrEqualTo(Date value) {
            addCriterion("opening_time <=", value, "openingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeIn(List<Date> values) {
            addCriterion("opening_time in", values, "openingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeNotIn(List<Date> values) {
            addCriterion("opening_time not in", values, "openingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeBetween(Date value1, Date value2) {
            addCriterion("opening_time between", value1, value2, "openingTime");
            return (Criteria) this;
        }

        public Criteria andOpeningTimeNotBetween(Date value1, Date value2) {
            addCriterion("opening_time not between", value1, value2, "openingTime");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNull() {
            addCriterion("project_type is null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNotNull() {
            addCriterion("project_type is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeEqualTo(String value) {
            addCriterion("project_type =", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotEqualTo(String value) {
            addCriterion("project_type <>", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThan(String value) {
            addCriterion("project_type >", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("project_type >=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThan(String value) {
            addCriterion("project_type <", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThanOrEqualTo(String value) {
            addCriterion("project_type <=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLike(String value) {
            addCriterion("project_type like", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotLike(String value) {
            addCriterion("project_type not like", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIn(List<String> values) {
            addCriterion("project_type in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotIn(List<String> values) {
            addCriterion("project_type not in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeBetween(String value1, String value2) {
            addCriterion("project_type between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotBetween(String value1, String value2) {
            addCriterion("project_type not between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeIsNull() {
            addCriterion("bid_payment_mode is null");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeIsNotNull() {
            addCriterion("bid_payment_mode is not null");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeEqualTo(String value) {
            addCriterion("bid_payment_mode =", value, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeNotEqualTo(String value) {
            addCriterion("bid_payment_mode <>", value, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeGreaterThan(String value) {
            addCriterion("bid_payment_mode >", value, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeGreaterThanOrEqualTo(String value) {
            addCriterion("bid_payment_mode >=", value, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeLessThan(String value) {
            addCriterion("bid_payment_mode <", value, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeLessThanOrEqualTo(String value) {
            addCriterion("bid_payment_mode <=", value, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeLike(String value) {
            addCriterion("bid_payment_mode like", value, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeNotLike(String value) {
            addCriterion("bid_payment_mode not like", value, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeIn(List<String> values) {
            addCriterion("bid_payment_mode in", values, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeNotIn(List<String> values) {
            addCriterion("bid_payment_mode not in", values, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeBetween(String value1, String value2) {
            addCriterion("bid_payment_mode between", value1, value2, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPaymentModeNotBetween(String value1, String value2) {
            addCriterion("bid_payment_mode not between", value1, value2, "bidPaymentMode");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineIsNull() {
            addCriterion("bid_purchase_deadline is null");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineIsNotNull() {
            addCriterion("bid_purchase_deadline is not null");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineEqualTo(Date value) {
            addCriterion("bid_purchase_deadline =", value, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineNotEqualTo(Date value) {
            addCriterion("bid_purchase_deadline <>", value, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineGreaterThan(Date value) {
            addCriterion("bid_purchase_deadline >", value, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("bid_purchase_deadline >=", value, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineLessThan(Date value) {
            addCriterion("bid_purchase_deadline <", value, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("bid_purchase_deadline <=", value, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineIn(List<Date> values) {
            addCriterion("bid_purchase_deadline in", values, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineNotIn(List<Date> values) {
            addCriterion("bid_purchase_deadline not in", values, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineBetween(Date value1, Date value2) {
            addCriterion("bid_purchase_deadline between", value1, value2, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andBidPurchaseDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("bid_purchase_deadline not between", value1, value2, "bidPurchaseDeadline");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyIsNull() {
            addCriterion("tender_agency is null");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyIsNotNull() {
            addCriterion("tender_agency is not null");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyEqualTo(String value) {
            addCriterion("tender_agency =", value, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyNotEqualTo(String value) {
            addCriterion("tender_agency <>", value, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyGreaterThan(String value) {
            addCriterion("tender_agency >", value, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyGreaterThanOrEqualTo(String value) {
            addCriterion("tender_agency >=", value, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyLessThan(String value) {
            addCriterion("tender_agency <", value, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyLessThanOrEqualTo(String value) {
            addCriterion("tender_agency <=", value, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyLike(String value) {
            addCriterion("tender_agency like", value, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyNotLike(String value) {
            addCriterion("tender_agency not like", value, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyIn(List<String> values) {
            addCriterion("tender_agency in", values, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyNotIn(List<String> values) {
            addCriterion("tender_agency not in", values, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyBetween(String value1, String value2) {
            addCriterion("tender_agency between", value1, value2, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andTenderAgencyNotBetween(String value1, String value2) {
            addCriterion("tender_agency not between", value1, value2, "tenderAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyIsNull() {
            addCriterion("proxy_agency is null");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyIsNotNull() {
            addCriterion("proxy_agency is not null");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyEqualTo(String value) {
            addCriterion("proxy_agency =", value, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyNotEqualTo(String value) {
            addCriterion("proxy_agency <>", value, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyGreaterThan(String value) {
            addCriterion("proxy_agency >", value, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyGreaterThanOrEqualTo(String value) {
            addCriterion("proxy_agency >=", value, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyLessThan(String value) {
            addCriterion("proxy_agency <", value, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyLessThanOrEqualTo(String value) {
            addCriterion("proxy_agency <=", value, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyLike(String value) {
            addCriterion("proxy_agency like", value, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyNotLike(String value) {
            addCriterion("proxy_agency not like", value, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyIn(List<String> values) {
            addCriterion("proxy_agency in", values, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyNotIn(List<String> values) {
            addCriterion("proxy_agency not in", values, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyBetween(String value1, String value2) {
            addCriterion("proxy_agency between", value1, value2, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andProxyAgencyNotBetween(String value1, String value2) {
            addCriterion("proxy_agency not between", value1, value2, "proxyAgency");
            return (Criteria) this;
        }

        public Criteria andContactPersonIsNull() {
            addCriterion("contact_person is null");
            return (Criteria) this;
        }

        public Criteria andContactPersonIsNotNull() {
            addCriterion("contact_person is not null");
            return (Criteria) this;
        }

        public Criteria andContactPersonEqualTo(String value) {
            addCriterion("contact_person =", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotEqualTo(String value) {
            addCriterion("contact_person <>", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonGreaterThan(String value) {
            addCriterion("contact_person >", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonGreaterThanOrEqualTo(String value) {
            addCriterion("contact_person >=", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLessThan(String value) {
            addCriterion("contact_person <", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLessThanOrEqualTo(String value) {
            addCriterion("contact_person <=", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLike(String value) {
            addCriterion("contact_person like", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotLike(String value) {
            addCriterion("contact_person not like", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonIn(List<String> values) {
            addCriterion("contact_person in", values, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotIn(List<String> values) {
            addCriterion("contact_person not in", values, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonBetween(String value1, String value2) {
            addCriterion("contact_person between", value1, value2, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotBetween(String value1, String value2) {
            addCriterion("contact_person not between", value1, value2, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNull() {
            addCriterion("contact_phone is null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNotNull() {
            addCriterion("contact_phone is not null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneEqualTo(String value) {
            addCriterion("contact_phone =", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotEqualTo(String value) {
            addCriterion("contact_phone <>", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThan(String value) {
            addCriterion("contact_phone >", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("contact_phone >=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThan(String value) {
            addCriterion("contact_phone <", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("contact_phone <=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLike(String value) {
            addCriterion("contact_phone like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotLike(String value) {
            addCriterion("contact_phone not like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIn(List<String> values) {
            addCriterion("contact_phone in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotIn(List<String> values) {
            addCriterion("contact_phone not in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneBetween(String value1, String value2) {
            addCriterion("contact_phone between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotBetween(String value1, String value2) {
            addCriterion("contact_phone not between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andFoxIsNull() {
            addCriterion("fox is null");
            return (Criteria) this;
        }

        public Criteria andFoxIsNotNull() {
            addCriterion("fox is not null");
            return (Criteria) this;
        }

        public Criteria andFoxEqualTo(String value) {
            addCriterion("fox =", value, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxNotEqualTo(String value) {
            addCriterion("fox <>", value, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxGreaterThan(String value) {
            addCriterion("fox >", value, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxGreaterThanOrEqualTo(String value) {
            addCriterion("fox >=", value, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxLessThan(String value) {
            addCriterion("fox <", value, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxLessThanOrEqualTo(String value) {
            addCriterion("fox <=", value, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxLike(String value) {
            addCriterion("fox like", value, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxNotLike(String value) {
            addCriterion("fox not like", value, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxIn(List<String> values) {
            addCriterion("fox in", values, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxNotIn(List<String> values) {
            addCriterion("fox not in", values, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxBetween(String value1, String value2) {
            addCriterion("fox between", value1, value2, "fox");
            return (Criteria) this;
        }

        public Criteria andFoxNotBetween(String value1, String value2) {
            addCriterion("fox not between", value1, value2, "fox");
            return (Criteria) this;
        }

        public Criteria andEMailIsNull() {
            addCriterion("e_mail is null");
            return (Criteria) this;
        }

        public Criteria andEMailIsNotNull() {
            addCriterion("e_mail is not null");
            return (Criteria) this;
        }

        public Criteria andEMailEqualTo(String value) {
            addCriterion("e_mail =", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotEqualTo(String value) {
            addCriterion("e_mail <>", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThan(String value) {
            addCriterion("e_mail >", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThanOrEqualTo(String value) {
            addCriterion("e_mail >=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThan(String value) {
            addCriterion("e_mail <", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThanOrEqualTo(String value) {
            addCriterion("e_mail <=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLike(String value) {
            addCriterion("e_mail like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotLike(String value) {
            addCriterion("e_mail not like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailIn(List<String> values) {
            addCriterion("e_mail in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotIn(List<String> values) {
            addCriterion("e_mail not in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailBetween(String value1, String value2) {
            addCriterion("e_mail between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotBetween(String value1, String value2) {
            addCriterion("e_mail not between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private SGCCProjectDetailExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(SGCCProjectDetailExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public SGCCProjectDetailExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectIdLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClosingTimeEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("closing_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClosingTimeNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("closing_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClosingTimeGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("closing_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClosingTimeGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("closing_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClosingTimeLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("closing_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andClosingTimeLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("closing_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOpeningTimeEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("opening_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOpeningTimeNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("opening_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOpeningTimeGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("opening_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOpeningTimeGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("opening_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOpeningTimeLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("opening_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOpeningTimeLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("opening_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectTypeEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectTypeNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectTypeGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectTypeGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectTypeLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectTypeLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("project_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPaymentModeEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_payment_mode = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPaymentModeNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_payment_mode <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPaymentModeGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_payment_mode > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPaymentModeGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_payment_mode >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPaymentModeLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_payment_mode < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPaymentModeLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_payment_mode <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPurchaseDeadlineEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_purchase_deadline = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPurchaseDeadlineNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_purchase_deadline <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPurchaseDeadlineGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_purchase_deadline > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPurchaseDeadlineGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_purchase_deadline >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPurchaseDeadlineLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_purchase_deadline < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBidPurchaseDeadlineLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("bid_purchase_deadline <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderAgencyEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_agency = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderAgencyNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_agency <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderAgencyGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_agency > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderAgencyGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_agency >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderAgencyLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_agency < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTenderAgencyLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("tender_agency <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProxyAgencyEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("proxy_agency = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProxyAgencyNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("proxy_agency <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProxyAgencyGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("proxy_agency > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProxyAgencyGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("proxy_agency >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProxyAgencyLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("proxy_agency < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProxyAgencyLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("proxy_agency <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPersonEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_person = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPersonNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_person <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPersonGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_person > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPersonGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_person >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPersonLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_person < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPersonLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_person <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPhoneEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_phone = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPhoneNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_phone <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPhoneGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_phone > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPhoneGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_phone >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPhoneLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_phone < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andContactPhoneLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("contact_phone <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFoxEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("fox = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFoxNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("fox <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFoxGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("fox > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFoxGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("fox >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFoxLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("fox < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFoxLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("fox <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andEMailEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("e_mail = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andEMailNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("e_mail <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andEMailGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("e_mail > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andEMailGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("e_mail >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andEMailLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("e_mail < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andEMailLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("e_mail <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeNotEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeGreaterThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeLessThanColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(SGCCProjectDetail.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table sgcc_project_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table sgcc_project_detail
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sgcc_project_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}